// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhikbskmtjeqfsitdnbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoaWtic2ttdGplcWZzaXRkbmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTUzMjUsImV4cCI6MjA2Mjk3MTMyNX0.CrEuPJpAGnr506dKsB6UfYLGeAuXqMBbtwI21lgCshA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);